### PR TITLE
Fix caching for Liberty config layer.

### LINKED ISSUE #168: Layer caching for config files
## What happened?

At the moment, the Config layer will always cache it's contents.

```
Open Liberty Config: Reusing cached layer
```

Thus if you make changes to external config, user features, or config from the app, it won't reload on subsequent builds. You have to delete the cache and re-run the build.

## Why?

This happens for two reasons:

1. When the layer contributor is created, we set an empty list of metadata. The metadata is what is compared to determine if the layer contributor should re-run or if the layer can be re-used. Since it's empty, it always matches and is always reused.

```
contributor := libpak.NewLayerContributor(
		"Open Liberty Config",
		map[string]interface{}{},
		libcnb.LayerTypes{
			Launch: true,
		})
```

2. We are running multiple tasks within the same layer contributor. This means that the layer contributor metadata applies to all of those tasks as a single unit. i.e. you cache all or re-run all.

We should probably split these tasks out into different layer contributors so they cache independently. That will make selecting metadata for them easier. The metadata should be something like a hash of the config file, which can detect if the files have changed.

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

### PR DESCRIPTION
**Pull request by hibell**
## Summary
Fixes #168. Fix caching of the base layer so that users do not need to clear the cache to update their config.

## Use Cases
Allows users to update their Liberty server config without clearing their cache.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

File: internal/util/file.go [hunk 1]
```diff
@@ -18,6 +18,7 @@ package util
 
 import (
 	"fmt"
+	"github.com/paketo-buildpacks/libpak/sherpa"
```
Comment (dmikusa) [inline internal/util/file.go:21]: This is minor, but I think you can remove some more code if you replace some of these methods with other `sherpa.*` methods.

For example:

- There exist methods to [check if files/directories exist](https://github.com/paketo-buildpacks/libpak/blob/main/sherpa/exists.go)
- There exists a [method to copy a file](https://github.com/paketo-buildpacks/libpak/blob/main/sherpa/copy_file.go).

There does not exist a copy directory method, but if you want to send a PR over, I'd be happy to add that to sherpa so you don't have to maintain it here. This is all optional, just thought I'd point it out.

File: liberty/base.go [hunk 2]
```diff
@@ -313,6 +321,13 @@ func (b Base) contributeConfigTemplates(layer libcnb.Layer) error {
 	for _, entry := range entries {
 		err := func() error {
 			srcPath := filepath.Join(srcDir, entry.Name())
+
+			// Check if a custom template was provided in a binding
+			if binding, ok := binding.SecretFilePath(entry.Name()); ok {
```
Comment (dmikusa) [inline liberty/base.go:326]: This is probably not a good idea from a security standpoint. It should be assumed that a binding contains sensitive information. As such you shouldn't copy them into the container image. A container image, stored in a registry, may have a wider audience than is intended for the secret information.

This also makes the binding baked into the image, so you can't change it at runtime. You can change bindings at runtime though, so it is less flexible.

Processing bindings is something that should be done during a helper/exec.d process at runtime before the app starts up.

**Comment by hibell** [comment]
@dmikusa Created PR paketo-buildpacks/libpak#174 to add `CopyDir` to sherpa. Currently working on updating the Liberty CNB to use sherpa functions.

File: liberty/base.go (hunk 2 above)
Comment (hibell) [reply liberty/base.go:328]: @dmikusa We need the `server.xml` to be generated at build time so that the Liberty runtime can do the feature installation. Instead of using a binding to provide the templates, can we have just mount a directory containing the templates to `/templates` similar to how we do iFixes and feature installs? We can also provide a warning to not to put secrets in these templates like we do when we copy any server config the user provides during the build.

If users need to provide any sensitive information, they can provide the `server.xml` with the sensitive information in the binding which is done at runtime.

Comment (dmikusa) [reply liberty/base.go:328]: I would leave that call up to you and @kevin-ortega, I consider you the subject matter experts. If you think that provides a reasonable user experience, then I'm OK with it. I think you could always add something to the buildpack later too if it becomes an issue. Like a way to provide the secret data through bindings and have it replaced at runtime (maybe it's mapped from binding to env variable & env variables are looked up in the config, or something like that). 

The biggest thing to consider though is that removing the binding support would be a breaking change so we'd have to trigger another major version bump. If there's a way you could do both so that you could retain the binding support in its present state as "deprecated" that would be preferred. It would put off having another major release since we just had one recently.

**Comment by dmikusa** [comment]
I'm OK with the changes now. Thanks for updating & using sherpa. Two things need to happen before we can merge this:

1. We need to cut a new release of libpak & update this PR to use the latest version.
2. Resolve conflicts. I think merging #260 created some minor conflicts.

Thanks

**Comment by hibell** [comment]
@dmikusa Thanks. PR has been updated.

**Review by dmikusa — APPROVED** [review]
